services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"


  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"

  redis-service:
    image: redis
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    command:
      - "redis-server"
    ports:
        - "6379:6379"