spring:
  application:
    name: strongnostr
    version: '1.0.0'
    description: Nostr-based fitness tracking application

server:
  port: 8080

data:
  mongodb:
    uri: mongodb://localhost:27017/strongnostr
    auto-index-creation: true
    field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

jwt:
  secret: super-secret-key-which-needs-to-be-long-enough-for-security
  access-token-expiration: 3600000
  refresh-token-expiration: 604800
  issuer: strongnostr

crypto:
  provider: BouncyCastle
  curve: secp256k1
  key-size: 256

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    doc-expansion: none
    disable-swagger-default-url: true
  show-actuator: false

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG