spring:
  application:
    name: strongnostr

  data:
    mongodb:
      uri: mongodb://localhost:27017/strongnostr
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  jwt:
    secret: super-secret-key
    expiration: 86400000

  crypto:
    provider: BouncyCastle
    curve: secp256k1
    key-size: 256
